/** Google Sheets 바인딩 Apps Script. 관리자 비밀번호는 Script Properties의 ADMIN_PASSWORD에 설정합니다. */
var CASE_HEADERS=['CaseID','생성일시','담당자','신청자정보(JSON)','매칭프로그램목록(JSON)','현재상태','최종수정일시','컨트랙터ID','배정일시'];
var HISTORY_HEADERS=['CaseID','타임스탬프','이전상태','새상태','메모','담당자'];
var CONTRACTOR_HEADERS=['컨트랙터ID','이름','연락처','액세스코드','계약시작일','계약서Drive링크','건당단가','활성여부','생성일시','최종수정일시'];
var PAYMENT_HEADERS=['CaseID','컨트랙터ID','하청비지급액','하청비지급일','하청비지급상태','정부정산수령액','정부정산수령일','정부정산수령상태'];
function doGet(e){try{var q=String(e.parameter.query||'').trim();return out_(q?{success:true,cases:findCases_(q)}:{success:false,error:'CaseID 또는 전화번호가 필요합니다.'});}catch(x){return out_({success:false,error:x.message});}}
function doPost(e){try{var d=JSON.parse((e.postData&&e.postData.contents)||'{}'),a=d.action;if(a==='createCase')return out_(createCase_(d));if(a==='updateStatus')return out_(updateStatus_(d));if(a==='adminLogin')return out_({success:admin_(d)});if(!admin_(d))return out_({success:false,error:'관리자 인증이 필요합니다.'});if(a==='registerContractor')return out_(registerContractor(d));if(a==='updateContractor')return out_(updateContractor(d.contractorId,d));if(a==='listContractors')return out_({success:true,contractors:getContractors_()});if(a==='getUnassignedCases')return out_({success:true,cases:getUnassignedCases()});if(a==='assignCase')return out_(assignCaseToContractor(d.caseId,d.contractorId));if(a==='dashboard')return out_({success:true,summary:getDashboardSummary(d.delayDays)});if(a==='subPayment')return out_(recordSubPayment(d.caseId,d.amount,d.date));if(a==='govReimbursement')return out_(recordGovReimbursement(d.caseId,d.amount,d.date));if(a==='paymentCandidates')return out_({success:true,cases:paymentCandidates_()});return out_({success:false,error:'지원하지 않는 요청입니다.'});}catch(x){return out_({success:false,error:x.message});}}
function out_(v){return ContentService.createTextOutput(JSON.stringify(v)).setMimeType(ContentService.MimeType.JSON);}function admin_(d){var p=PropertiesService.getScriptProperties().getProperty('ADMIN_PASSWORD');return !!p&&String(d.adminPassword||'')===p;}
function ensure_(name,headers){var ss=SpreadsheetApp.getActive(),sh=ss.getSheetByName(name);if(!sh){sh=ss.insertSheet(name);sh.appendRow(headers);sh.setFrozenRows(1);return sh;}var old=sh.getRange(1,1,1,Math.max(1,sh.getLastColumn())).getValues()[0];headers.forEach(function(h){if(old.indexOf(h)<0){sh.getRange(1,sh.getLastColumn()+1).setValue(h);old.push(h);}});return sh;}
function sheets_(){return {cases:ensure_('Cases',CASE_HEADERS),history:ensure_('StatusHistory',HISTORY_HEADERS),contractors:ensure_('Contractors',CONTRACTOR_HEADERS),payments:ensure_('Payments',PAYMENT_HEADERS)};}function map_(sh){var h=sh.getRange(1,1,1,sh.getLastColumn()).getValues()[0],m={};h.forEach(function(x,i){m[x]=i;});return m;}function rows_(sh){var v=sh.getDataRange().getValues(),m={};v[0].forEach(function(x,i){m[x]=i;});return {v:v,m:m};}function json_(v,f){try{return JSON.parse(v);}catch(e){return f;}}function date_(v){return v instanceof Date?Utilities.formatDate(v,Session.getScriptTimeZone(),'yyyy-MM-dd HH:mm:ss'):String(v||'');}function findRow_(sh,col,value){var x=rows_(sh),i;for(i=1;i<x.v.length;i++)if(String(x.v[i][x.m[col]])===String(value))return {row:i+1,data:x.v[i],m:x.m};return null;}
function createCase_(d){if(!d.applicant||!d.applicant.name||!d.applicant.phone)throw Error('이름과 전화번호는 필수입니다.');var s=sheets_(),now=new Date(),id='EV-'+Utilities.formatDate(now,Session.getScriptTimeZone(),'yyyyMMdd-HHmmss')+'-'+Math.floor(100+Math.random()*900);s.cases.appendRow([id,now,d.agent||'',JSON.stringify(d.applicant),JSON.stringify(d.programs||[]),'대기',now,'','']);s.history.appendRow([id,now,'','대기','케이스 생성',d.agent||'']);return {success:true,caseId:id};}
function updateStatus_(d){var s=sheets_(),r=findRow_(s.cases,'CaseID',d.caseId);if(!r||!d.newStatus)throw Error('유효한 케이스와 상태가 필요합니다.');var old=r.data[r.m['현재상태']],now=new Date();if(old!==d.newStatus){s.cases.getRange(r.row,r.m['현재상태']+1).setValue(d.newStatus);s.cases.getRange(r.row,r.m['최종수정일시']+1).setValue(now);s.history.appendRow([d.caseId,now,old,d.newStatus,d.note||'',d.agent||'']);}return {success:true};}
function findCases_(q){var s=sheets_(),x=rows_(s.cases),h=rows_(s.history),needle=String(q).toLowerCase(),digits=needle.replace(/\D/g,''),out=[];for(var i=1;i<x.v.length;i++){var r=x.v[i],a=json_(r[x.m['신청자정보(JSON)']],{}),id=String(r[x.m.CaseID]);if(id.toLowerCase().indexOf(needle)<0&&(!digits||String(a.phone||'').replace(/\D/g,'').indexOf(digits)<0))continue;out.push(caseObj_(r,x.m,h.v,h.m));}return out;}
function caseObj_(r,m,hv,hm){var id=r[m.CaseID],hist=[];for(var j=1;j<hv.length;j++)if(String(hv[j][hm.CaseID])===String(id))hist.push({timestamp:date_(hv[j][hm['타임스탬프']]),previousStatus:hv[j][hm['이전상태']],newStatus:hv[j][hm['새상태']],note:hv[j][hm['메모']],agent:hv[j][hm['담당자']]});return {caseId:id,createdAt:date_(r[m['생성일시']]),applicant:json_(r[m['신청자정보(JSON)']],{}),programs:json_(r[m['매칭프로그램목록(JSON)']],[]),status:r[m['현재상태']],contractorId:r[m['컨트랙터ID']],assignedAt:date_(r[m['배정일시']]),updatedAt:date_(r[m['최종수정일시']]),history:hist};}
function registerContractor(d){var x=d.contractor||d;if(!x.name||!x.phone)throw Error('업체명과 연락처는 필수입니다.');var s=sheets_(),now=new Date(),id='CTR-'+Utilities.formatDate(now,Session.getScriptTimeZone(),'yyyyMMdd')+'-'+Math.floor(100+Math.random()*900),code=x.accessCode||Utilities.getUuid().slice(0,8).toUpperCase();s.contractors.appendRow([id,x.name,x.phone,code,x.contractStart||'',x.contractLink||'',Number(x.unitPrice||0),x.active===false?'아니오':'예',now,now]);return {success:true,contractorId:id,accessCode:code};}
function updateContractor(id,d){var r=findRow_(sheets_().contractors,'컨트랙터ID',id),x=d.contractor||d;if(!r)throw Error('업체를 찾을 수 없습니다.');var sh=sheets_().contractors,m=r.m;[['이름','name'],['연락처','phone'],['액세스코드','accessCode'],['계약시작일','contractStart'],['계약서Drive링크','contractLink'],['건당단가','unitPrice']].forEach(function(p){if(x[p[1]]!==undefined)sh.getRange(r.row,m[p[0]]+1).setValue(p[0]==='건당단가'?Number(x[p[1]]):x[p[1]]);});if(x.active!==undefined)sh.getRange(r.row,m['활성여부']+1).setValue(x.active?'예':'아니오');sh.getRange(r.row,m['최종수정일시']+1).setValue(new Date());return {success:true};}
function getContractors_(){var s=sheets_(),x=rows_(s.contractors),cases=rows_(s.cases),out=[];for(var i=1;i<x.v.length;i++){var r=x.v[i],id=r[x.m['컨트랙터ID']],assigned=0,done=0,durations=[];for(var j=1;j<cases.v.length;j++)if(String(cases.v[j][cases.m['컨트랙터ID']])===String(id)){assigned++;if(cases.v[j][cases.m['현재상태']]==='시공완료'||cases.v[j][cases.m['현재상태']]==='정산완료'){done++;var start=cases.v[j][cases.m['배정일시']],end=cases.v[j][cases.m['최종수정일시']];if(start instanceof Date&&end instanceof Date)durations.push(Math.round((end-start)/86400000));}}out.push({contractorId:id,name:r[x.m['이름']],phone:r[x.m['연락처']],accessCode:r[x.m['액세스코드']],contractStart:date_(r[x.m['계약시작일']]),contractLink:r[x.m['계약서Drive링크']],unitPrice:r[x.m['건당단가']],active:r[x.m['활성여부']]==='예',assigned:assigned,completed:done,averageDays:durations.length?Math.round(durations.reduce(function(a,b){return a+b;},0)/durations.length):null});}return out;}
function getUnassignedCases(){var s=sheets_(),x=rows_(s.cases),h=rows_(s.history);return x.v.slice(1).filter(function(r){return !r[x.m['컨트랙터ID']];}).map(function(r){return caseObj_(r,x.m,h.v,h.m);});}
function assignCaseToContractor(caseId,contractorId){var s=sheets_(),c=findRow_(s.cases,'CaseID',caseId),t=findRow_(s.contractors,'컨트랙터ID',contractorId);if(!c||!t||t.data[t.m['활성여부']]!=='예')throw Error('유효한 활성 업체와 케이스가 필요합니다.');var old=c.data[c.m['현재상태']],now=new Date();s.cases.getRange(c.row,c.m['컨트랙터ID']+1,1,2).setValues([[contractorId,now]]);s.cases.getRange(c.row,c.m['현재상태']+1).setValue('배정됨');s.cases.getRange(c.row,c.m['최종수정일시']+1).setValue(now);s.history.appendRow([caseId,now,old,'배정됨','컨트랙터 배정: '+t.data[t.m['이름']],'관리자']);return {success:true};}
function getDashboardSummary(delayDays){var s=sheets_(),x=rows_(s.cases),h=rows_(s.history),limit=Number(delayDays||7),statuses=['대기','배정됨','시공중','시공완료','서류제출완료','정산완료'],counts={},delayed=[];statuses.forEach(function(k){counts[k]=0;});for(var i=1;i<x.v.length;i++){var r=x.v[i],state=r[x.m['현재상태']],updated=r[x.m['최종수정일시']],isDelayed=r[x.m['컨트랙터ID']]&&updated instanceof Date&&(new Date().getTime()-updated.getTime())/86400000>=limit&&['시공완료','정산완료'].indexOf(state)<0;counts[state]=(counts[state]||0)+1;if(isDelayed)delayed.push(caseObj_(r,x.m,h.v,h.m));}return {statusCounts:counts,contractors:getContractors_().map(function(c){return {name:c.name,assigned:c.assigned,completed:c.completed};}),delayed:delayed,delayDays:limit};}
function paymentRow_(caseId,contractorId){var sh=sheets_().payments,r=findRow_(sh,'CaseID',caseId);if(!r){sh.appendRow([caseId,contractorId||'',0,'','대기',0,'','대기']);r=findRow_(sh,'CaseID',caseId);}return {sh:sh,r:r};}function recordSubPayment(caseId,amount,date){var c=findRow_(sheets_().cases,'CaseID',caseId);if(!c)throw Error('케이스를 찾을 수 없습니다.');var p=paymentRow_(caseId,c.data[c.m['컨트랙터ID']]),m=p.r.m;p.sh.getRange(p.r.row,m['하청비지급액']+1,1,3).setValues([[Number(amount),date||new Date(),'완료']]);updateStatus_({caseId:caseId,newStatus:'정산완료',note:'하청비 지급 처리',agent:'관리자'});return {success:true};}function recordGovReimbursement(caseId,amount,date){var c=findRow_(sheets_().cases,'CaseID',caseId);if(!c)throw Error('케이스를 찾을 수 없습니다.');var p=paymentRow_(caseId,c.data[c.m['컨트랙터ID']]),m=p.r.m;p.sh.getRange(p.r.row,m['정부정산수령액']+1,1,3).setValues([[Number(amount),date||new Date(),'완료']]);return {success:true};}function paymentCandidates_(){var s=sheets_(),x=rows_(s.cases),pay=rows_(s.payments),out=[];for(var i=1;i<x.v.length;i++){var r=x.v[i];if(r[x.m['현재상태']]!=='시공완료')continue;var pr=findRow_(s.payments,'CaseID',r[x.m.CaseID]);if(!pr||pr.data[pr.m['하청비지급상태']]!=='완료')out.push(caseObj_(r,x.m,[],{}));}return out;}
